name: React Native CI

on:
  push:
    branches:
      - main # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main # Trigger on pull requests to 'main'

jobs:
  android-build:
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build APK
        run: eas build --profile preview --platform android --non-interactive --clear-cache

      - name: Store apk download URL in env variable
        run: echo "apk_url=$(eas build:list --json --limit=1 --platform=android |  jq -r .[0].artifacts.buildUrl)" >> $GITHUB_ENV
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_MAIL_SEND}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          to: khaidemdenish@gmail.com,khaidemdenish@gmail.com
          from: Developer
          secure: true
          body: ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }} APK URL -> ${{ env.apk_url }}
          ignore_cert: true
          convert_markdown: true
          attachments: attachments.zip,git.diff,./dist/static/*.js
          priority: low

      - name: Download apk file
        uses: suisei-cn/actions-download-file@v1
        id: downloadfile # Remember to give an ID if you need the output
        with:
          url: 'Downloading APK from [this](${{ env.apk_url }})!'
          target: public/
          auto-match: true
      - name: LIST DIR
        run: ls -R

      - uses: thedoctor0/zip-release@master
        with:
          path: public/
          filename: demo-app.zip

      - name: Create Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}

      - name: Upload asset to Github release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./demo-app.zip
          asset_name: demo-app-v${{ github.run_number }}.zip
          asset_content_type: application/zip
# delete-release:
#   runs-on: ubuntu-latest
#   needs: update
#   steps:
#     - uses: dev-drprasad/delete-older-releases@v0.2.0
#       with:
#         repo: dork7/react_native_app
#         keep_latest: 2
#           # delete_tag_pattern: beta
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# - name: Set up JDK
#   uses: actions/setup-java@v3
#   with:
#     distribution: 'zulu'
#     java-version: '17' # Android requires JDK 11 or above

# - name: Build Android
#   run: ./gradlew assembleDebug # Builds debug APK
#   working-directory: android/
